# Generated by Django 5.2.3 on 2025-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='No description for this item', max_length=1000),
        ),
    ]
